// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqojeesjtgfcftpnzaet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxb2plZXNqdGdmY2Z0cG56YWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDI3ODgsImV4cCI6MjA1OTMxODc4OH0.MTWWnZo0G24CFn4H5XPamrFVeDgmPcq_0iOT2nSa9jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);